govuk-one-login/ipv-cri-check-hmrc-front

src/app/check/controllers/national-insurance-number.js, tests/imposter/private-api-config.yaml, tests/imposter/private-api.yaml, tests/unit/src/app/check/controllers/national-insurance-number.test.js
- Update OpenAPI config from ipv-cri-check-hmrc-api
- Update Imposter config based upon OpenAPI config
- Update API call and unit tests
OpenAPI config use a payload of a format `{ nino: "AABC"}` not `{ key: "nino", value: "AABC"}`
=> fix: Use correct /check API call

src/app/check/fields.js, src/lib/validator.js, src/locales/cy/fields.yml, src/locales/en/fields.yml, tests/browser/features/error-bad-nino.feature, tests/browser/pages/nino.js, tests/browser/step_definitions/national-insurance-number.js, tests/unit/src/lib/validator.test.js
adding validation to the Nino page.
OJ-1922
added the validator, and attached it to the field
[update to field and validator
nino validator edge case unit tests
front-end testing for the nino validation.
so that the UI has validation
[OJ-1922] - https://govukverify.atlassian.net/browse/OJ-1922
[OJ-1922]: https://govukverify.atlassian.net/browse/OJ-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1922-Add-validator-for-NINO

package-lock.json, package.json
- Update to 4.7 of govuk-frontend
- Update to latest version of hmpo packages
- breaking changes are all to do with dropping support for Node 12
=> chore: Update govuk-frontend and hmpo* packages

.github/workflows/post-merge-to-build.yml, .github/workflows/post-merge-to-dev.yml
- Updated post-merge workflow to use devplatform-upload-action-ecr@1.2.0
- Required for canary deployments across Identity
- [IPS-493](https://govukverify.atlassian.net/browse/IPS-493)
- [IPS-532](https://govukverify.atlassian.net/browse/IPS-532)
- Image successfully pushed to dev, with commit tag, by manually triggering workflow:
https://github.com/govuk-one-login/ipv-cri-check-hmrc-front/actions/runs/7932030114
[IPS-493]: https://govukverify.atlassian.net/browse/IPS-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-532]: https://govukverify.atlassian.net/browse/IPS-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-493: Update post-merge workflow to use devplatform-upload-action-ecr

.prettierignore, deploy/template.yaml
- Implement Subscription filter for CSLS logging
- Add CSLSEGRESS ARNs for all the environments
- Add subscription filters for the ECS and API GW
- Add subscription filters to inject logs into splunk
- [IPS-676](https://govukverify.atlassian.net/browse/IPS-676)
[IPS-676]: https://govukverify.atlassian.net/browse/IPS-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-676: Implement subscription filter for CSLS logging

src/app/check/controllers/abandon.js, tests/imposter/private-api.yaml, tests/unit/src/app/check/controllers/abandon.test.js
Added the header `content-type: application/json` to the `/abandon` API request as this is a required header. Without it, we are getting an "invalid media type" error being returned by AWS.
=> Add content-type header to /abandon request

src/app/check/controllers/abandon.js, tests/unit/src/app/check/controllers/abandon.test.js
When specifying a content-type, AWS requires that the body of specified content-type to set. This PR sets the request body as an empty JSON to satisfy AWSs behavior.
=> Added empty request body to /abandon request

src/app/check/controllers/abandon.js, tests/imposter/private-api-config.yaml, tests/unit/src/app/check/controllers/abandon.test.js
The post body was set incorrectly so this PR fixes that. Additionally, the content-type is enforced in the imposter config.
=> Fix post body to /abandon endpoint

src/locales/cy/pages.yml, src/locales/en/pages.yml
Removed '- ... GOV.UK' from the page titles.
This was raised as a accessibility issue due to inconsistent page title naming. We use the CE template to standardise the titles, so we now only need to provide the page title itself. Format here: https://github.com/HMPO/hmpo-components/blob/master/components/hmpo-template.njk#L13
- [OJ-2529](https://govukverify.atlassian.net/browse/OJ-2529)
[OJ-2529]: https://govukverify.atlassian.net/browse/OJ-2529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove - GOV.UK from the page titles to use the CE template as intended

package-lock.json, package.json
Reverts govuk-one-login/ipv-cri-check-hmrc-front#146
6.5.0 broke the frontend:
=> Revert "BAU: Bump hmpo-components from 6.4.0 to 6.5.0"

package-lock.json, package.json, src/locales/cy/fields.yml, src/locales/en/fields.yml
- Upgrades hmpo-components
- Adds default value for prefix for text fields
=> BAU: Upgrades hmpo-components

.github/dependabot.yaml
Dependabot running daily isn't consistent with how the other repos are configured and makes it harder for us to keep track of.
=> BAU: Change dependabot to run weekly instead of daily

deploy/template.yaml
Added WAF association as part of the cloudfront work
There is a requirement for a WAF
- [IPS-728](https://govukverify.atlassian.net/browse/IPS-728)
[IPS-728]: https://govukverify.atlassian.net/browse/IPS-728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-728 HMRC Check WAF association

package-lock.json, package.json, src/app.js
Added `frontend-vital-signs` package and initialised it within app.js
To collect node metrics to help us with observability around performance and system health.
CloudWatch logs showing the logging from `frontend-vital-signs`:
No frontend breakages occurred:
- [OJ-2759](https://govukverify.atlassian.net/browse/OJ-2759)
[OJ-2759]: https://govukverify.atlassian.net/browse/OJ-2759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2759: Use `frontend-vital-signs` package

deploy/template.yaml
Added metrics for the logging for `frontend-vital-signs`
The log messages provided by the `frontend-vital-signs` package is to help us monitor performance metrics such as average response times and how many requests we get per second. At the moment, that information is just a log message in the CloudWatch logs. This PR creates `MetricFilter`s so that we can visual the data.
Tested each individual metric and it is showing correctly in CloudWatch
- [OJ-2759](https://govukverify.atlassian.net/browse/OJ-2759)
[OJ-2759]: https://govukverify.atlassian.net/browse/OJ-2759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2759: Create metrics for `frontend-vital-signs` package

deploy/template.yaml
- Added resources to enable canary deployments, as detailed by devplatform in https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance
- Resources include:
-  Deployment controller 
-  Second target group for green deployment
-  Canary deployment nested stack
-  5xx alarm for target group
- Removed FrontEcsService from LowContainer alarm (When deploying stage 1, CodeDeploy creates new tasks and this transition starts with 0 containers, inadvertently triggering the LowContainer alarm), see https://github.com/govuk-one-login/ipv-cri-bav-front/pull/316
- First of 2 PRs to enable canary deployments
- [IPS-532](https://govukverify.atlassian.net/browse/IPS-532)
- [IPS-552](https://govukverify.atlassian.net/browse/IPS-552)
[IPS-532]: …
=> IPS-552: Add resources for canary deployment (stage 1)

deploy/template.yaml
To be merged after https://github.com/govuk-one-login/ipv-cri-check-hmrc-front/pull/248
- Updated TaskDefintion
- Removed NetworkConfiguration and LoadBalancers property from your ECS Service resource. 
- Second of 2 PRs to enable canary deployments
- To enable canary deployments
- Other config commented out to avoid errors, see step 7: https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance
- [IPS-532](https://govukverify.atlassian.net/browse/IPS-532)
- [IPS-552](https://govukverify.atlassian.net/browse/IPS-552)
[IPS-532]: https://govukverify.atlassian.net/browse/IPS-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-552]: https://govukverify.atlassian.net/browse/IPS-552?atlOrigin=ey …
=> IPS-552: Enable canary deployment (stage 2)

package-lock.json, package.json
common-express updated to 7.0.0
Bug fix for the `redirect_uri` being undefined
- [OJ-2724](https://govukverify.atlassian.net/browse/OJ-2724)
[OJ-2724]: https://govukverify.atlassian.net/browse/OJ-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2724: Update common-express to 7.0.0

.github/workflows/push-test-docker-image.yml
Add push to main trigger
So that the test image is deployed when a PR is merged to main
- [OJ-2752](https://govukverify.atlassian.net/browse/OJ-2752)
[OJ-2752]: https://govukverify.atlassian.net/browse/OJ-2752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2752: Add push to main trigger

deploy/template.yaml, tests/browser/post-merge.Dockerfile, tests/browser/run-tests-post-merge.sh
* Updated Dockerfile to copy `run-tests-post-merge.sh` into the container as `run-tests.sh`. This is because the pipeline expects the name to be `run-tests.sh` and it could not run without it. 
* Make core stub URL a stack output instead because the PL does not have access to read SSM parameters then also updated `run-tests-post-merge.sh` to fetch core stub URL from stack output instead of SSM
- [OJ-2750](https://govukverify.atlassian.net/browse/OJ-2750)
[OJ-2750]: https://govukverify.atlassian.net/browse/OJ-2750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2750: Updates to run tests using run-tests.sh

deploy/template.yaml, tests/browser/.env.example, tests/browser/environment-variables.md, tests/browser/pages/relying-party.js, tests/browser/run-tests-post-merge.sh
- Renamed `ENV` to `ENVIRONMENT` because it causes confusion
- Sets `USE_LOCAL_API` in post-merge-run-tests
- Use new SSM param to set `RELYING_PARTY_URL` (see [PR](https://github.com/govuk-one-login/ipv-cri-pipeline-deployment/pull/220))
For tests to pass
- [OJ-2791](https://govukverify.atlassian.net/browse/OJ-2791)
[OJ-2791]: https://govukverify.atlassian.net/browse/OJ-2791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2791: Fix env vars for post merge testing

src/app/check/steps.js, tests/browser/features/could-not-match-national-insurance.feature, tests/browser/step_definitions/could-not-match-national-insurance.js, tests/imposter/private-api-config.yaml
Added a step/route to use the abandon controller prior to routing to the callback.
Emit the IPV_HMRC_RECORD_CHECK_CRI_ABANDONED event when a user selects the "Try another way to prove your identity" option on the retry screen.
Also, When a user went to the 'how-continue-national-insurance' page, even if they selected 'Enter national insurance number ...', when they clicked Continue the abandon state machine would be invoked. Only abandon if the user selects 'Try another way...'
- [OJ-2924](https://govukverify.atlassian.net/browse/OJ-2924)
[OJ-2924]: https://govukverify.atlassian.net/browse/OJ-2924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2924: Invoke Abandon state machine on retry exit

tests/browser/pages/relying-party.js
Change method call `getStartingURLForStub1` to `getStartingURLForStub`.
Tests pass locally, but fail when ran through the pipeline. Looks to be a typo in the code that only fails when USE_LOCAL_API is false.
Looks to have been a bug added in: https://github.com/govuk-one-login/ipv-cri-check-hmrc-front/pull/308/files#diff-7acb2c3a3f5f5c67524cfafe4c7994bff12390a6bdfde7f659b3859cb0bbee74R28
=> Bug fix: Fix tests failing in the pipeline

package-lock.json, package.json
Bump govuk-frontend to version 4.9.0
There have been changes to crown logo.
- [OJ-2914](https://govukverify.atlassian.net/browse/OJ-2914)
[OJ-2914]: https://govukverify.atlassian.net/browse/OJ-2914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build: bump govuk-frontend to version 4.9.0

src/app/check/controllers/national-insurance-number.js, tests/imposter/private-api-config.yaml, tests/unit/src/app/check/controllers/national-insurance-number.test.js
Added support for http 200 with requestRetry
BE now returns http 200 with a body requestRetry: true
- [OJ-2921](https://govukverify.atlassian.net/browse/OJ-2921)
[OJ-2921]: https://govukverify.atlassian.net/browse/OJ-2921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: handle http 200 with retry

src/app/check/controllers/national-insurance-number.js, tests/imposter/private-api.yaml, tests/unit/src/app/check/controllers/national-insurance-number.test.js
Removed http 422 check
The API now returns a HTTP 200 with requestRetry in the body so the 422 check is redundant.
- [OJ-2921](https://govukverify.atlassian.net/browse/OJ-2921)
[OJ-2921]: https://govukverify.atlassian.net/browse/OJ-2921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove 422 status check

package-lock.json, package.json, src/app.js
Added overload-protection library to app.js
To prevent node from accepting too many connections and putting itself into a blocking state.
- [OJ-2864](https://govukverify.atlassian.net/browse/OJ-2864)
[OJ-2864]: https://govukverify.atlassian.net/browse/OJ-2864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2864: Add overload-protection

deploy/template.yaml
Using the minium invocation count as baseline 300 invocations / day => 1440 minutes / day is approximately about 0.21 invocations per minute. The period has be adjusted to allow for enough activity 15 mins i.e 900 secs
Traffic last [90days](https://gds.splunkcloud.com/en-GB/app/gds-050-digital-Identity/search?dispatch.sample_ratio=1&display.page.search.mode=smart&workload_pool=standard_perf&q=search%20index%3D%22gds_di_production%22%20source%3D%22*check-hmrc-cri-front-*%22%20sourcetype%3D%22aws%3Acloudwatchlogs%3Aapi-access-*%22%20di_account_name_enriched%3D%22di-ipv-cri-check-hmrc-prod%22%20%0A%7C%20timechart%20span%3D1d%20count%20as%20requests&earliest=-90d%40d&latest=now&display.page.search.tab=visualizations&display.general.type=visualizations&sid=1734449016.69326)
``` …
```
=> OJ-2872: And new alarm definition for 80%  5xx errors fe api-gateway

src/app.js
Increased maxEventLoopDelay
It looks like the threshold has been set too low which is causing the 503s. Core have seen spikes that aren’t being logged by the vital signs package so where they have the same average event loop delay as us they have set the max to 400 and are not seeing any issues. 
We have made this change in address in it is reducing the number of 503s
- [OJ-2992](https://govukverify.atlassian.net/browse/OJ-2992)
[OJ-2992]: https://govukverify.atlassian.net/browse/OJ-2992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2992: Increase maxEventLoopDelay

deploy/template.yaml
The stack parameters are difficult to change, there is no reason for MaxContainerCount to be one and it needs increasing. Removing the param and hardcoding the alarm threshold to 13.
So FEHighContainerTaskCountWarning does not alarm when we deploy a new FE update to Prod & Build.
- [OJ-2942](https://govukverify.atlassian.net/browse/OJ-2942)
[OJ-2942]: https://govukverify.atlassian.net/browse/OJ-2942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2942: Remove MaxContainerCount Stack parameter

.github/workflows/code-quality.yml, package-lock.json, package.json, src/app.js
- Replace HMPO-app with common-express bootstrap
- Upgraded other HMPO packages
- Updated pre-commit GHA so we are able to set node-version
We want to replace HMPO-app with common-express bootstrap so that we have more control over what's in it and can fix issues that we have been wanting to fix
No regression
- [OJ-2938](https://govukverify.atlassian.net/browse/OJ-2938)
[OJ-2938]: https://govukverify.atlassian.net/browse/OJ-2938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2938: replace hmpo-app with common-express bootstrap

src/locales/cy/default.yml, src/locales/en/default.yml
- Updated `serviceName` to " " for both English and Welsh for the common express condition to trigger 
https://github.com/user-attachments/assets/8ed45b7e-2fd5-4147-8cab-39a68df37936
Based on the accessibility testing documented [here](https://govukverify.atlassian.net/wiki/spaces/A/pages/4461756473/Page+titles+in+GOV.UK+One+Login)
- [OJ-2975](https://govukverify.atlassian.net/browse/OJ-2975)
[OJ-2975]: https://govukverify.atlassian.net/browse/OJ-2975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2975: Update serviceName to trigger common express condition

deploy/template.yaml
Scale Out
- Changed adjustmentType to PercentChange...
- Modified scaling adjustments
- Changes alarm threshold to 60
Scale In
- Increase cooldown from 60 seconds to 300
- Modified scaling adjustments
- Changed alarm threshold to 60
Brought the scaling policy inline with Address and KBV.
- [OJ-2732](https://govukverify.atlassian.net/browse/OJ-2732)
[OJ-2732]: https://govukverify.atlassian.net/browse/OJ-2732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2732: Adjust scaling policy

.github/workflows/post-merge-to-dev.yml, Dockerfile, deploy/template.yaml, dev.Dockerfile, local.Dockerfile, package-lock.json, package.json
Currently load balancers are configured to call healthcheck endpoints to ensure that the target is healthy and ready to receive traffic, but also we need to implement configuration to for the task definition.
So as to enable it replace unhealthy tasks before the point of them being requested by the load balancer.
Below is healthcheck inside the dockerfile
- [OJ-2946](https://govukverify.atlassian.net/browse/OJ-2946)
[OJ-2946]: https://govukverify.atlassian.net/browse/OJ-2946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2946: ECS task healthcheck

.pre-commit-config.yaml, .secrets.baseline, deploy/template.yaml
- Added capacity mapping for ECS task counts 
- Removed condition on creating auto scaling policy so it applies to all envs
- This adds a new Predicitive scaling policy which will scale the number of instances based on some AWS created  algorithm using the previous traffic patterns as input. See this for more information:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-predictive-scaling.html
- The policy is in `Forecast Mode` only so we can understand its behaviour. The predictive scaling policy will not take any action, see below in dev:
- Update pre-commit config and fixed linting issue:
```
E3020 'Dimensions' should not be included with 'Metrics'
deploy/template.yaml:1225:7
```
- Cost saving
- To be more Environmentally friendly
- Reliability for users …
=> IPS-1332: Predictive scaling for ECS in forecast mode

deploy/template.yaml
CPU increased to 2048 and memory to 4096
Due to the way that nodeJS uses the eventLoop, the performance of the container performs better if there is a second CPU able to offload some of async threads.
- [OJ-3041](https://govukverify.atlassian.net/browse/OJ-3041)
[OJ-3041]: https://govukverify.atlassian.net/browse/OJ-3041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: increase cpu to 2048 and memory to 4096

deploy/template.yaml
Load balancer updates for the FMS firewall - Re-enable WAF association in dev
This is still required
- [IPS-1436](https://govukverify.atlassian.net/browse/IPS-1436)
Application happening today
[IPS-1436]: https://govukverify.atlassian.net/browse/IPS-1436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1436 re-associate web ACL

.github/workflows/scan-repo.yml, src/app/check/fields.js, src/lib/validator.js, src/locales/cy/fields.yml, src/locales/en/fields.yml, tests/browser/features/error-bad-nino.feature, tests/browser/step_definitions/national-insurance-number.js, tests/unit/lib/helpers.js, tests/unit/src/lib/validator.test.js
- Add new validation for the invalid prefix and suffix characters for nino
- Update existing validation so that the new validation is not overwritten
- Update unit and integration tests
- Updated the `validation.js` to check the following scenarios first to ensure its a valid NiNo before validating against the "invalidCharacter" regex: has too many characters, has too few characters, does not follow the 2 letters, 6 numbers, 1 letter format
https://github.com/user-attachments/assets/0e22a9b6-c59e-40aa-8b19-4ed9bac28821
- Added welsh translation
So that users can be informed when entering National Insurance number containing invalid characters
- [OJ-3007](https://govukverify.atlassian.net/browse/OJ-3007)
[OJ-3007]: https://govukverify.atlassian.net/browse/OJ-3007?atlOrigin=eyJpIjoiNWRkNTljN …
=> OJ-3007: Amend Nino error message

src/app/check/controllers/enter-national-insurance-number.js, src/app/check/steps.js, src/lib/config.js, src/locales/cy/default.yml, src/locales/cy/pages.yml, src/locales/en/default.yml, src/locales/en/pages.yml, src/views/check/enter-national-insurance-number.njk, tests/browser/pages/abandon.js, tests/browser/pages/could-not-match-national-insurance.js, tests/browser/pages/nino.js, tests/unit/src/app/check/controllers/national-insurance-number.test.js
Changes the base route `/check` -> `/`
Also changed `/national-insurance-number` -> `/enter-national-insurance-number`
URL paths changed;
`/check/national-insurance-number` → `/enter-national-insurance-number `
`/check/could-not-match-national-insurance` → `/could-not-match-national-insurance`
`/check/how-continue-national-insurance` → `/how-continue-national-insurance`
UCD review - So that it aligns with the expected URL structure 
- [OJ-2973](https://govukverify.atlassian.net/browse/OJ-2973)
[OJ-2973]: https://govukverify.atlassian.net/browse/OJ-2973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2973: Remove check from url path

package-lock.json, package.json, src/app/check/index.js, src/app/check/middleware/session-check-middleware.js, tests/browser/features/error-missing-session.feature, tests/browser/pages/error.js, tests/browser/step_definitions/errors.js, tests/unit/src/app/check/middleware/session-check-middleware.test.js
Since https://github.com/govuk-one-login/ipv-cri-check-hmrc-front/pull/354 - Removing `/check` from the base url we have since an increase in 5XX errors. This is due to users now accessing `/` redirect to the `/enter-national-insurance-page` and can enter a nino resulting in a 5XX error as no session exists. This is the same issue across CRI's e.g. address-cri, it's more frequent in apps without a base route. 
Highlighted line is where the PR was merged.
- Adds `sessionCheckMiddleware` that does a basic check on the request to see if it has been through OAuth prior to this. If it has not, an error is thrown that will result in a`401` and an error page. 
- Bumped common-express to include missing auth params error handling.
Current behaviour;
1. User directly accesses our apps entry point …
=> Spike: Testing CRI entry session validation

deploy/template.yaml
Set NODE_ENV env var to production for deployed environments
By not explicitly setting there is a possibility that some of our dependencies are operating in development mode which might be impacting our performance
I have regression tested with this change and seen no errors in logs or impact to the user journey.
- [OJ-3109](https://govukverify.atlassian.net/browse/OJ-3109)
[OJ-3109]: https://govukverify.atlassian.net/browse/OJ-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3109: Set NODE_ENV to production

.github/workflows/check-pr.yml, .github/workflows/scan-repo.yml
- Scan repo workflow no longer runs unit tests on pull requests (unit tests were ran twice on each PR). The coverage artefact is now used from the `Check PR` workflow.
- `coverage-run-id` is passed into the `SonarCloud` action for none PRs so it does not run the `Await coverage report` step.
- Added workflow_dispatch to Scan Repo action. 
Unit tests were running twice on every PR. 
`Await coverage report` was added to the sonarcloud github action which broke our Scan Repo action when running on a schedule. Passing in the workflow id to the action prevents this from happening. 
- [OJ-3108](https://govukverify.atlassian.net/browse/OJ-3108)
[OJ-3108]: https://govukverify.atlassian.net/browse/OJ-3108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3108: Scan schedule erroring

tests/browser/package-lock.json, tests/browser/package.json, tests/browser/pages/relying-party.js, tests/browser/run-tests-post-merge.sh, tests/browser/step_definitions/relying-party.js, tests/browser/support/testUserConfig.js
Swap to use headless core stub for post merge tests
New stub was introduced to reduce complexity.
Update tests to pass in overrides rather than use excel sheet row numbers.
- [OJ-2994](https://govukverify.atlassian.net/browse/OJ-2994)
[OJ-2994]: https://govukverify.atlassian.net/browse/OJ-2994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2994: Swap to use headless core stub for post merge tests

tests/browser/run-tests-post-merge.sh
Use `TEST_ENVIRONMENT` instead of stack outputs
Because the common pipeline role doesn't have access to describe the front stack
`TEST_ENVIRONMENT` is exported by the [deploy pipeline](https://github.com/govuk-one-login/devplatform-utils/blob/5cdb0d36d0e2ee540afad252ed7a204cd223c633/sam-deploy-pipeline/template.yaml#L3177)
Front pipeline step still passes when using new test image
- [OJ-3187](https://govukverify.atlassian.net/browse/OJ-3187)
[OJ-3187]: https://govukverify.atlassian.net/browse/OJ-3187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3187: Use TEST_ENVIRONMENT instead of stack outputs

deploy/template.yaml
Enable `may2025RebrandEnabled` in integration
To align with the overall implementation plan and as confirmed that integration enablement supports E2E testing beginning W/C 14th July.
- [OJ-3239](https://govukverify.atlassian.net/browse/OJ-3239)
[OJ-3239]: https://govukverify.atlassian.net/browse/OJ-3239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3239: Enable branding in int

package-lock.json, package.json
- Bumped `frontend-ui` package to include the FEC fix
Before - currently on stubs:
https://github.com/user-attachments/assets/11f66925-5042-40c4-9542-d91340204f6b
Now - FEC fix:
https://github.com/user-attachments/assets/e58bcb2d-0166-46dd-92c2-07618d3901fc
To enable branding changes.
- [OJ-3322](https://govukverify.atlassian.net/browse/OJ-3322)
[OJ-3322]: https://govukverify.atlassian.net/browse/OJ-3322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3322: chore - update frontend-ui package with the latest FEC changes

deploy/template.yaml
Set `may2025RebrandEnabled` to true for `prod`
Enable branding changes in production. 
- [OJ-3282](https://govukverify.atlassian.net/browse/OJ-3282)
[OJ-3282]: https://govukverify.atlassian.net/browse/OJ-3282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3282: Enable new branding in prod

src/locales/cy/default.yml, src/locales/en/default.yml
Remove text fields relating to rebranding in `default.yml` for both languages
The common-express, which introduces the brand changes holds the default fields for govuk text in both languages, the change is to prevent any risk of overriding or misalignment in the future.
- [OJ-3236](https://govukverify.atlassian.net/browse/OJ-3236)
[OJ-3236]: https://govukverify.atlassian.net/browse/OJ-3236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3236: Remove text fields relating to footer and banners

deploy/template.yaml
- Enabled drop_invalid_header_fields on frontend ALB
- This setting checks that header names conform to `[-A-Za-z0-9]+` and drops any that do not. This is beneficial as it will protect the frontend application from potentially unsafe header keys.
- [OJ-3356](https://govukverify.atlassian.net/browse/OJ-3356)
[OJ-3356]: https://govukverify.atlassian.net/browse/OJ-3356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3356: Enable drop_invalid_header_fields on ALB

deploy/template.yaml
S3 buckets should have policies that require requests to use SSL/TLS, by having a policy that denies HTTP requests. 
This means that data in transit is encrypted which is a security best practise https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html#transit
=> OJ-3355: Update AccessLogsBucketPolicy to Deny non https request

deploy/template.yaml
- Applied FMS regional policy tags to API Gateway & load balancer in dev+build+staging
- The new FMS policy improves the security stance of the CRI
- OJ-3446
=> OJ-3446: Apply FMS tags to APIGW + ELB outside int/prod
