- .github/workflows/unit-tests.yml
Run unit tests workflow on merge to `main`
> feat(fe): Run unit tests GHA on main

- .github/workflows/post-merge-to-build.yml
- deploy/template.yaml
This PR is for getting the NINO Check Frontend deployed to AWS
- [OJ-1966](https://govukverify.atlassian.net/browse/OJ-1966)
[OJ-1966]: https://govukverify.atlassian.net/browse/OJ-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (BAU): Deploy Frontend to AWS

- .github/workflows/post-merge-to-build.yml
> BAU: Name `ARTIFACT_BUCKET` to `ARTIFACT_BUCKET_NAME`

- deploy/template.yaml
> Disable CSLS logging for all envs

- deploy/template.yaml
> BAU: Removed `,` from URL

- .github/workflows/browser.yml
- local.Dockerfile
- tests/browser/Dockerfile
- tests/browser/package-lock.json
- tests/browser/package.json
- tests/docker/compose.yml
Add GHA to run browser tests using docker compose
> feat: Add GHA to run browser tests

- src/locales/cy/fields.yml
> feat: Update Welsh language content

- .github/workflows/post-merge-to-dev.yml
Added GHA to deploy to dev as one does not currently exist so we do not have an automated way to deploy this repo to the dev env. 
So that we can deploy the check front to the dev environment
> BAU: Added post-merge-to-dev.yml

- .github/workflows/browser.yml
- .github/workflows/post-merge-to-build.yml
- .github/workflows/post-merge-to-dev.yml
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- .secrets.baseline
- CODEOWNERS
- Dockerfile
- deploy/template.yaml
IPS-296 Added Dynatrace Integration
Updated Codeowners
Added Dynatrace layer to Dockerfile
Updated Template
Added checkov and cfn-lint to pre-commit hooks
Fixed github workflows ordering
modified:   .github/workflows/browser.yml
modified:   .github/workflows/post-merge-to-build.yml
modified:   .github/workflows/post-merge-to-dev.yml
modified:   .github/workflows/pre-commit.yml
modified:   .pre-commit-config.yaml
modified:   .secrets.baseline
modified:   CODEOWNERS
modified:   Dockerfile
modified:   deploy/template.yaml
IPS-296 Added Dynatrace Integration
Updated Codeowners
Added Dynatrace layer to Dockerfile
Updated Template
Added checkov and cfn-lint to pre-commit hooks
Fixed github workflows ordering
- [IPS-296](https://govukverify.atlassian.net/browse/IPS-296)
[IPS-296]: …
> IPS-296 Added Dynatrace Integratio

- README.md
Added the docker commands to run the front end with the same memory and CPU as production
It changed to be able to run the front end with docker
> Updated README with docker instruction

- .secrets.baseline
- deploy/template.yaml
`template.yaml`
Added step scaling policy as done in address and kbv.
Performance testing, fargate was reaching 100% cpu utilisation.
- [OJ-2160](https://govukverify.atlassian.net/browse/OJ-2160)
[OJ-2160]: https://govukverify.atlassian.net/browse/OJ-2160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2160: Added step scaling policy

- .github/dependabot.yaml
> chore: Add dependabot config

- .eslintignore
- .eslintrc.js
- .github/workflows/pre-commit.yml
- .github/workflows/unit-tests.yml
- .pre-commit-config.yaml
- .prettierignore
- .prettierrc.json
- .secrets.baseline
- jest.config.js
- package-lock.json
- package.json
- tests/browser/step_definitions/national-insurance-number.js
- tests/browser/step_definitions/relying-party.js
- tests/browser/support/setup.js
- tests/unit/lib/helpers.js
- tests/unit/src/app/check/controllers/national-insurance-number.test.js
- tests/unit/src/lib/settings.test.js
Apply standardised repo config from other repos
- Update pre-commit hooks
- Add missing hooks
- Remove a misconfigured Checkov hook
- Add an ESLint hook
- Address linting issues
- Use the prettier and jest plugins in ESLint
- Apply the recommended rules and styles for jest only for test files
- Install dev dependencies before running pre-commit to get ESLint plugins
- Allow unused variables if their names start with an underscore in test files
- Do linting as part of the pre-commit checks
- Update the linting commands
- Update the `.secrets.baseline` file to exclude specific keywords and files
- Update `package.json` to remove duplicated or unnecessary config
- Update linting and testing packages
> OJ-1495: Update repo config

- jest.config.js
- sonar-project.properties
Ignore form-wizard config in sonar.properties
> test: Add config filepaths to sonar.exclusions

- .github/workflows/post-merge-to-build.yml
- .github/workflows/post-merge-to-dev.yml
- Added checkout step
- Removed matrix
- Fix SAM validate path error
- [IPS-493](https://govukverify.atlassian.net/browse/IPS-493)
- Workflow deployed to dev successfully: https://github.com/govuk-one-login/ipv-cri-check-hmrc-front/actions/runs/7972619832
[IPS-493]: https://govukverify.atlassian.net/browse/IPS-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-493: Fix workflow

- src/locales/cy/default.yml
- src/locales/en/default.yml
Footer content and interactions changed to match standard journey behaviour
YAML content files have been updated.
Footer content should remain the same across the user journey to meet [the new **Consistent Help** WCAG 2.2 criteria](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help).
> CNUCD: Update footer to standardise link content

- src/app/check/controllers/national-insurance-number.js
- src/app/check/fields.js
- src/app/check/steps.js
- src/locales/cy/fields.yml
- src/locales/cy/pages.yml
- src/locales/en/fields.yml
- src/locales/en/pages.yml
- src/views/check/could-not-match-national-insurance.njk
- tests/browser/features/could-not-match-national-insurance.feature
- tests/browser/package-lock.json
- tests/browser/pages/could-not-match-national-insurance.js
- tests/browser/pages/index.js
- tests/browser/step_definitions/could-not-match-national-insurance.js
- tests/browser/step_definitions/national-insurance-number.js
- tests/imposter/private-api.yaml
- tests/unit/src/app/check/controllers/national-insurance-number.test.js
OJ-2244 added new page could-not-match-national-insurance
[OJ-2244] NINO retry page
added new page could-not-match-national-insurance
Added tests for this new page
to allow a retry attempt on the NINO journey
- [OJ-2244](https://govukverify.atlassian.net/browse/OJ-XXXX)](https://govukverify.atlassian.net/browse/OJ-2244)
[OJ-2244]: https://govukverify.atlassian.net/browse/OJ-2244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2244]: https://govukverify.atlassian.net/browse/OJ-2244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2244 added new page could-not-match-national-insurance

- src/app/check/controllers/abandon.js
- src/app/check/fields.js
- src/app/check/steps.js
- src/lib/config.js
- src/locales/cy/fields.yml
- src/locales/cy/pages.yml
- src/locales/en/fields.yml
- src/locales/en/pages.yml
- src/views/check/abandon.njk
- src/views/check/could-not-match-national-insurance.njk
- src/views/check/national-insurance-number.njk
- tests/browser/features/abandon-nino-cri.feature
- tests/browser/features/happy.feature
- tests/browser/pages/abandon.js
- tests/browser/pages/index.js
- tests/browser/pages/nino.js
- tests/browser/step_definitions/abandon.js
- tests/browser/step_definitions/national-insurance-number.js
- tests/imposter/private-api-config.yaml
- tests/imposter/private-api.yaml
- tests/unit/src/app/check/controllers/abandon.test.js
[OJ-2347]Create abandon page
Created the abandon page 
Added the abandon page and associated feature tests 
To be included in sprint work.
[OJ-2347](https://govukverify.atlassian.net/browse/OJ-2347)
[OJ-2347]: https://govukverify.atlassian.net/browse/OJ-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2347]: https://govukverify.atlassian.net/browse/OJ-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 0J-2347: Create Abandon Page

- src/locales/cy/fields.yml
- src/locales/cy/pages.yml
- src/locales/en/fields.yml
- src/locales/en/pages.yml
[OJ-2413] NINO | FE | Align Retry Screen with MVP Designs
updated text fields
updated text fields and added title
to match the design documents
- [OJ-2413](https://govukverify.atlassian.net/browse/OJ-2413)
[OJ-2413]: https://govukverify.atlassian.net/browse/OJ-2413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2413]: https://govukverify.atlassian.net/browse/OJ-2413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2413: Updated Text fields

- .prettierignore
- deploy/template.yaml
Added monitoring and alerting for NINO check front end to cloud formation template
Added monitoring and alerting for NINO check front end to cloud formation template
- [IPS-650](https://govukverify.atlassian.net/browse/IPS-650)
- [IPS-664](https://govukverify.atlassian.net/browse/IPS-664)
[IPS-650]: https://govukverify.atlassian.net/browse/IPS-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-664]: https://govukverify.atlassian.net/browse/IPS-664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-664 IPS-650 monitoring and alerting NINO check front end

- src/app/check/controllers/national-insurance-number.js
- src/app/check/fields.js
- src/lib/validator.js
- src/locales/cy/fields.yml
- src/locales/cy/pages.yml
- src/locales/en/fields.yml
- src/locales/en/pages.yml
- src/views/check/could-not-match-national-insurance.njk
- src/views/check/national-insurance-number.njk
- tests/unit/src/lib/validator.test.js
OJ-2414 NINO | FE | Align What is Your NINO Screen with MVP Designs
updated Locales with updated wording,
updated validator and controller, to handle new nino input behaviour
updated 2 views to reflect the changes in ui
changes to the controller and Validator, were to handle whitespace and lowercase letters
[OJ-2414] (https://govukverify.atlassian.net/browse/OJ-2414)
[OJ-2414]: https://govukverify.atlassian.net/browse/OJ-2414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  Align What is Your NINO Screen with MVP Designs

- deploy/template.yaml
Updated incorrect topic name
To fix issue with deployment when obsolete alarm stack is removed
BAU
> BAU fix incorrect topic name

- deploy/template.yaml
- Removed target tracking step policy
- Updated scale in and out policies
- Updated alarms for scale in and out policies
Tested different combinations of autoscaling and the one that gave the best performance (Least errors/ responsive scaling in and out) was the following. I have tested this by running the performance test against my dev stack.
- [OJ-2435](https://govukverify.atlassian.net/browse/OJ-2435)
[OJ-2435]: https://govukverify.atlassian.net/browse/OJ-2435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2435 Errors in Front end API Gateway

- package-lock.json
- package.json
- src/app.js
- src/assets/scss/application.scss
Update language toggle dependency, and use new nujucks global
- [OJ-2564](https://govukverify.atlassian.net/browse/OJ-2564)
[OJ-2564]: https://govukverify.atlassian.net/browse/OJ-2564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Use updated language toggle and cri-common-express

- package-lock.json
- package.json
Updates the analytics package version to latest
The latest package release contains several bug fixes required by the analytics team to unblock their QA. The package has also been renamed to improve compliance.
This is the first major version push of the package, from this point forward dependabot should pick up new version releases.
Sibling PR of https://github.com/govuk-one-login/ipv-cri-bav-front/pull/216
> Update analytics package to v1.0.3 + change analytics package name

- deploy/template.yaml
Updated welsh toggle feature flag to be enabled in all environments apart from integration and production
Enable E2E testing in staging for the welsh toggle
- [OJ-2596](https://govukverify.atlassian.net/browse/OJ-2596)
[OJ-2596]: https://govukverify.atlassian.net/browse/OJ-2596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2596: Enable Welsh Toggle in envs apart from prod and int

- package-lock.json
- package.json
- src/app/check/controllers/abandon.js
- src/app/check/controllers/national-insurance-number.js
- src/lib/config.js
- tests/unit/lib/helpers.js
- tests/unit/src/app/check/controllers/abandon.test.js
- tests/unit/src/app/check/controllers/national-insurance-number.test.js
Adds personal details headers to API calls
As a part of cloudfront work to better track fraud
- [OJ-2534](https://govukverify.atlassian.net/browse/OJ-2534)
[OJ-2534]: https://govukverify.atlassian.net/browse/OJ-2534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2534: Adds personal details headers to API calls

- src/locales/en/default.yml
error title fix Post UCD Review
error summary text
UCD requested change
[- [OJ-2560](https://govukverify.atlassian.net/browse/OJ-2560)]
[OJ-2560]: https://govukverify.atlassian.net/browse/OJ-2560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2560-error-title-fix-Post-UCD-Review

- package-lock.json
- package.json
[OJ-2571] Accessibility Fix - Focus on Error Summary
updated di-ipv-cri-common-express to include the fix
[OJ-2571](https://govukverify.atlassian.net/browse/OJ-2571)
[OJ-2571]: https://govukverify.atlassian.net/browse/OJ-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2571]: https://govukverify.atlassian.net/browse/OJ-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> updated common express version to include the fix.

- deploy/template.yaml
Update the supportManualUrl from confluence to the published URL
As a DI 2nd line support engineer
I want to have the runbook for an alarm close at hand
So that I can quickly understand how to respond
- [OJ-2316](https://govukverify.atlassian.net/browse/OJ-2316)
[OJ-2316]: https://govukverify.atlassian.net/browse/OJ-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2316: Update the supportManualUrl to the published URL

- .github/workflows/post-merge-to-build.yml
- .github/workflows/post-merge-to-dev.yml
[IPS-821] PR Title --> Ips 821 - upload action ecr updated to 1.2.6
post merge to build and post merge to dev updated with upload actioN version 1.2.6. v was required with the newer version
updated to latest version
N/A
testing done in dev, see [IPS-821](https://govukverify.atlassian.net/browse/IPS-821) ticket to view this
[IPS-821](https://govukverify.atlassian.net/browse/IPS-821)
[IPS-821]: https://govukverify.atlassian.net/browse/IPS-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-821]: https://govukverify.atlassian.net/browse/IPS-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-821]: https://govukverify.atlassian.net/browse/IPS-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
> IPS-821 upload action ecr updated to v1.2.6

- deploy/template.yaml
Modified alarms for PagerDuty setup
- [OJ-2616](https://govukverify.atlassian.net/browse/OJ-2616)
[OJ-2616]: https://govukverify.atlassian.net/browse/OJ-2616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2616 - Modified alarms for PagerDuty setup

- deploy/template.yaml
- Rename the critical alert topic name. 
- Rename the critical alert topic name. 
- [OJ-2616](https://govukverify.atlassian.net/browse/OJ-2616)
[OJ-2616]: https://govukverify.atlassian.net/browse/OJ-2616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2616: Fix critical alerts topic name

- deploy/template.yaml
Removed a level of nesting from eventLoopUtilization metric filters. 
Metrics were not being created.
- [OJ-2759](https://govukverify.atlassian.net/browse/OJ-2759)
[OJ-2759]: https://govukverify.atlassian.net/browse/OJ-2759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2759: Amend metric filter for ECS Vital signs metric

- package-lock.json
- package.json
Bump common express to version 10
To get performance fixes from the new version 
- [OJ-2927](https://govukverify.atlassian.net/browse/OJ-2927)
[OJ-2927]: https://govukverify.atlassian.net/browse/OJ-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2927: Bump common express to version 10

- package-lock.json
- package.json
Upgrade common express to version 10.0.1
To receive the latest fixes from common express
- [OJ-2977](https://govukverify.atlassian.net/browse/OJ-2977)
[OJ-2977]: https://govukverify.atlassian.net/browse/OJ-2977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2977: chore - upgrade common express v10.0.1

- deploy/template.yaml
Turn on device intelligence for int and prod
- [OJ-3148](https://govukverify.atlassian.net/browse/OJ-3148)
[OJ-3148]: https://govukverify.atlassian.net/browse/OJ-3148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3148: Turn on device intelligence in int and prod

- package-lock.json
Ran `npm audit fix`
https://github.com/govuk-one-login/ipv-cri-check-hmrc-front/security/dependabot/33
- [OJ-3216](https://govukverify.atlassian.net/browse/OJ-3216)
[OJ-3216]: https://govukverify.atlassian.net/browse/OJ-3216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3216: Fix vulnerability

- .github/workflows/code-quality.yml
- .github/workflows/push-test-docker-image.yml
- .github/workflows/run-unit-tests.yml
- .github/workflows/scan-repo.yml
Upgrade github-actions to latest version
Upgraded addresses because there was a warning, wanted to keep all the fronts on the same version
> BAU: Upgrade github-actions to latest version

- tests/browser/package-lock.json
Ran audit fix
https://github.com/govuk-one-login/ipv-cri-check-hmrc-front/security/dependabot/37
- [OJ-3271](https://govukverify.atlassian.net/browse/OJ-3271)
[OJ-3271]: https://govukverify.atlassian.net/browse/OJ-3271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3271: Audit fix

- package-lock.json
- package.json
Upgrade eslint-plugin-jest
Before 
After
- [OJ-3330](https://govukverify.atlassian.net/browse/OJ-3330)
[OJ-3330]: https://govukverify.atlassian.net/browse/OJ-3330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3330: Upgrade eslint-plugin-jest

- .github/workflows/scan-repo.yml
Updates govuk-one-login/github-actions/code-quality/sonarcloud to commit 7bc197778553493ca4c6fb4a78caf3cfd03f8ccb
> BAU: Update sonarcloud action to latest version
